### ISSUE TITLE
[メイン画面]ファイル名を分かりやすくする

### ISSUE THREAD

**Issue by bot810** [NT-Dentsu/dentsuTools#48]
ファイル名が割と適当なのである程度機能に即したものにする

# ToDo

- [ ] index/cssフォルダのファイル名を変更
- [ ] index/jsフォルダのファイル名を変更
- [ ] index/imagesフォルダのファイル名を変更
- [ ] index/panel_customize/cssフォルダのファイル名を変更
- [ ] index/panel_customize/jsフォルダのファイル名を変更
- [ ] index/panel_customize/imagesフォルダのファイル名を変更

**Comment by KARASU-2000** [comment]
bot810のやる気がなくなったため対応しない
